name: PR Lint
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
jobs:
  prlint:
    uses: tradovate/web-team-tools/.github/workflows/lint_devel.yml@main
    secrets: inherit
    with:
      repo-name: application-ci
